site_name: CodersInventory
site_url: https://mydomain.org/mysite
nav:
  - Home: index.md
  - User Guide:
    - Writing your docs: llm/gpt2.md
    - Styling your docs: llm/llm.md
  - End:
    - bye: pagae_2.md

theme:

  name: material
  
  language: en

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  
  plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/hoopes" target="_blank" rel="noopener">Hoopes</a>. Created by <a href="https://github.com/your-username" target="_blank" rel="noopener">Your Name</a> and <a href="https://github.com/friend-username" target="_blank" rel="noopener">Friend's Name</a>. All rights reserved.


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js